-- =======================================
-- Howard County Sidewalk Planning System
-- Database schema init script
-- =======================================
-- Generated by scripts/export_db.sh
-- =======================================

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.11 (Ubuntu 16.11-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: topology; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA topology;


--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: postgis_topology; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis_topology WITH SCHEMA topology;


--
-- Name: calculate_offset_sign(double precision, text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.calculate_offset_sign(bearing double precision, side text) RETURNS integer
    LANGUAGE plpgsql IMMUTABLE
    AS $$
BEGIN
  CASE
    WHEN side IN ('left', 'west', 'south') THEN RETURN -1;
    WHEN side IN ('right', 'east', 'north') THEN RETURN 1;
    ELSE RETURN 1;
  END CASE;
END;
$$;


--
-- Name: get_road_bearing(public.geometry); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.get_road_bearing(geom public.geometry) RETURNS double precision
    LANGUAGE plpgsql IMMUTABLE
    AS $$
DECLARE
  start_point geometry;
  end_point geometry;
  dx FLOAT;
  dy FLOAT;
  bearing FLOAT;
BEGIN
  start_point := ST_StartPoint(geom);
  end_point := ST_EndPoint(geom);
  
  dx := ST_X(end_point) - ST_X(start_point);
  dy := ST_Y(end_point) - ST_Y(start_point);
  
  bearing := degrees(atan2(dy, dx));
  
  IF bearing < 0 THEN
    bearing := bearing + 360;
  END IF;
  
  RETURN bearing;
END;
$$;


SET default_table_access_method = heap;

--
-- Name: command_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.command_history (
    id integer NOT NULL,
    command_text text NOT NULL,
    parsed_json jsonb,
    sidewalk_id integer,
    scenario text,
    user_id text,
    success boolean DEFAULT true,
    error_message text,
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: command_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.command_history_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: command_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.command_history_id_seq OWNED BY public.command_history.id;


--
-- Name: county_boundary; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.county_boundary (
    id integer NOT NULL,
    name text DEFAULT 'Howard County'::text,
    state text DEFAULT 'Maryland'::text,
    geom public.geometry(Polygon,4326),
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: county_boundary_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.county_boundary_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: county_boundary_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.county_boundary_id_seq OWNED BY public.county_boundary.id;


--
-- Name: intersections_howard; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.intersections_howard (
    id integer NOT NULL,
    osm_id bigint,
    name text,
    traffic_signals boolean DEFAULT false,
    crossing boolean DEFAULT false,
    geom public.geometry(Point,4326),
    properties jsonb,
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: intersections_howard_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.intersections_howard_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: intersections_howard_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.intersections_howard_id_seq OWNED BY public.intersections_howard.id;


--
-- Name: roads_howard; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roads_howard (
    id integer NOT NULL,
    osm_id bigint,
    name text,
    highway text,
    surface text,
    lanes integer,
    maxspeed text,
    oneway boolean DEFAULT false,
    geom public.geometry(LineString,4326),
    properties jsonb,
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: roads_howard_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.roads_howard_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: roads_howard_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.roads_howard_id_seq OWNED BY public.roads_howard.id;


--
-- Name: scenarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scenarios (
    id integer NOT NULL,
    name text NOT NULL,
    description text,
    created_by text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


--
-- Name: scenarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.scenarios_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: scenarios_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.scenarios_id_seq OWNED BY public.scenarios.id;


--
-- Name: sidewalks_howard; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sidewalks_howard (
    id integer NOT NULL,
    name text,
    side text,
    width_m double precision DEFAULT 1.5,
    surface text,
    source text DEFAULT 'generated'::text,
    road_id integer,
    scenario text DEFAULT 'base'::text,
    status text DEFAULT 'proposed'::text,
    properties jsonb,
    geom public.geometry(LineString,4326),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


--
-- Name: sidewalks_howard_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sidewalks_howard_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sidewalks_howard_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sidewalks_howard_id_seq OWNED BY public.sidewalks_howard.id;


--
-- Name: command_history id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.command_history ALTER COLUMN id SET DEFAULT nextval('public.command_history_id_seq'::regclass);


--
-- Name: county_boundary id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.county_boundary ALTER COLUMN id SET DEFAULT nextval('public.county_boundary_id_seq'::regclass);


--
-- Name: intersections_howard id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.intersections_howard ALTER COLUMN id SET DEFAULT nextval('public.intersections_howard_id_seq'::regclass);


--
-- Name: roads_howard id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roads_howard ALTER COLUMN id SET DEFAULT nextval('public.roads_howard_id_seq'::regclass);


--
-- Name: scenarios id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenarios ALTER COLUMN id SET DEFAULT nextval('public.scenarios_id_seq'::regclass);


--
-- Name: sidewalks_howard id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sidewalks_howard ALTER COLUMN id SET DEFAULT nextval('public.sidewalks_howard_id_seq'::regclass);


--
-- Name: command_history command_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.command_history
    ADD CONSTRAINT command_history_pkey PRIMARY KEY (id);


--
-- Name: county_boundary county_boundary_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.county_boundary
    ADD CONSTRAINT county_boundary_pkey PRIMARY KEY (id);


--
-- Name: intersections_howard intersections_howard_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.intersections_howard
    ADD CONSTRAINT intersections_howard_pkey PRIMARY KEY (id);


--
-- Name: roads_howard roads_howard_osm_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roads_howard
    ADD CONSTRAINT roads_howard_osm_id_key UNIQUE (osm_id);


--
-- Name: roads_howard roads_howard_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roads_howard
    ADD CONSTRAINT roads_howard_pkey PRIMARY KEY (id);


--
-- Name: scenarios scenarios_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenarios
    ADD CONSTRAINT scenarios_name_key UNIQUE (name);


--
-- Name: scenarios scenarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenarios
    ADD CONSTRAINT scenarios_pkey PRIMARY KEY (id);


--
-- Name: sidewalks_howard sidewalks_howard_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sidewalks_howard
    ADD CONSTRAINT sidewalks_howard_pkey PRIMARY KEY (id);


--
-- Name: idx_boundary_geom; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_boundary_geom ON public.county_boundary USING gist (geom);


--
-- Name: idx_command_history_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_command_history_created ON public.command_history USING btree (created_at);


--
-- Name: idx_command_history_scenario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_command_history_scenario ON public.command_history USING btree (scenario);


--
-- Name: idx_intersections_geom; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_intersections_geom ON public.intersections_howard USING gist (geom);


--
-- Name: idx_roads_geom; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_roads_geom ON public.roads_howard USING gist (geom);


--
-- Name: idx_roads_highway; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_roads_highway ON public.roads_howard USING btree (highway);


--
-- Name: idx_roads_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_roads_name ON public.roads_howard USING btree (name);


--
-- Name: idx_sidewalks_geom; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sidewalks_geom ON public.sidewalks_howard USING gist (geom);


--
-- Name: idx_sidewalks_road_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sidewalks_road_id ON public.sidewalks_howard USING btree (road_id);


--
-- Name: idx_sidewalks_scenario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sidewalks_scenario ON public.sidewalks_howard USING btree (scenario);


--
-- Name: idx_sidewalks_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sidewalks_status ON public.sidewalks_howard USING btree (status);


--
-- Name: command_history command_history_sidewalk_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.command_history
    ADD CONSTRAINT command_history_sidewalk_id_fkey FOREIGN KEY (sidewalk_id) REFERENCES public.sidewalks_howard(id);


--
-- Name: sidewalks_howard sidewalks_howard_road_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sidewalks_howard
    ADD CONSTRAINT sidewalks_howard_road_id_fkey FOREIGN KEY (road_id) REFERENCES public.roads_howard(id);


--
-- PostgreSQL database dump complete
--


