#!/usr/bin/env bash
# =======================================
# Howard County Sidewalk Planning System
# Database export script
# =======================================
# Exports schema and seed from existing DB to:
#   - sql/init/001_schema.sql
#   - sql/init/002_seed.sql
# =======================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Load .env (manual parse)
if [ -f .env ]; then
    while IFS='=' read -r key value; do
        if [[ ! "$key" =~ ^[[:space:]]*# ]] && [[ -n "$key" ]] && [[ "$key" =~ ^[A-Z_]+ ]]; then
            value=$(echo "$value" | sed 's/#.*$//' | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//' | sed 's/^"\(.*\)"$/\1/' | sed "s/^'\(.*\)'$/\1/")
            export "$key=$value"
        fi
    done < .env
fi

if ! command -v pg_dump &> /dev/null; then
    echo -e "${RED}❌ pg_dump not found${NC}"
    echo "Install PostgreSQL client:"
    echo "  Ubuntu/Debian: sudo apt install postgresql-client"
    echo "  macOS: brew install postgresql"
    echo "  Or use pg_dump from Docker container"
    exit 1
fi

EXPORT_SCHEMA=false
EXPORT_SEED=false

if [ "$1" == "--schema-only" ]; then
    EXPORT_SCHEMA=true
elif [ "$1" == "--seed-only" ]; then
    EXPORT_SEED=true
elif [ "$1" == "--all" ] || [ -z "$1" ]; then
    EXPORT_SCHEMA=true
    EXPORT_SEED=true
else
    echo -e "${RED}❌ Unknown option: $1${NC}"
    echo "Usage:"
    echo "  $0 --schema-only   # schema only"
    echo "  $0 --seed-only     # seed data only"
    echo "  $0 --all           # schema + seed (default)"
    exit 1
fi

if [ -n "$DATABASE_URL" ]; then
    CONN="$DATABASE_URL"
    echo -e "${GREEN}ℹ️  Using DATABASE_URL${NC}"
else
    DB_HOST="${DATABASE_HOST:-127.0.0.1}"
    DB_PORT="${DATABASE_PORT:-5432}"
    DB_NAME="${DATABASE_NAME:-howard_sidewalk_db}"
    DB_USER="${DATABASE_USER:-appuser}"
    DB_PASSWORD="${DATABASE_PASSWORD}"
    
    if [ -z "$DB_PASSWORD" ]; then
        echo -e "${RED}❌ DATABASE_PASSWORD not set${NC}"
        exit 1
    fi
    
    CONN="postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME"
    echo -e "${GREEN}ℹ️  Connecting to $DB_HOST:$DB_PORT/$DB_NAME${NC}"
fi

mkdir -p sql/init

if [ "$EXPORT_SCHEMA" = true ]; then
    echo -e "${YELLOW}📤 Exporting schema...${NC}"
    
    pg_dump "$CONN" \
        --schema-only \
        --no-owner \
        --no-privileges \
        --no-tablespaces \
        --no-security-labels \
        --no-comments \
        > sql/init/001_schema.sql
    
    cat > sql/init/001_schema.sql.tmp << 'EOF'
-- =======================================
-- Howard County Sidewalk Planning System
-- Database schema init script
-- =======================================
-- Generated by scripts/export_db.sh
-- =======================================

EOF
    
    sed "s/\$(date '+%Y-%m-%d %H:%M:%S')/$(date '+%Y-%m-%d %H:%M:%S')/g" sql/init/001_schema.sql.tmp > sql/init/001_schema.sql.header
    
    grep -v '^\\restrict' sql/init/001_schema.sql | \
    grep -v '^\\connect' | \
    grep -v '^--\s*Dumped from' | \
    grep -v '^--\s*Dumped by' >> sql/init/001_schema.sql.header
    
    mv sql/init/001_schema.sql.header sql/init/001_schema.sql
    rm -f sql/init/001_schema.sql.tmp
    
    echo -e "${GREEN}✅ Schema exported to sql/init/001_schema.sql${NC}"
fi

if [ "$EXPORT_SEED" = true ]; then
    echo -e "${YELLOW}📤 Exporting seed data...${NC}"
    
    SEED_TABLES="${EXPORT_TABLES:-roads_howard,scenarios}"
    SEED_WHERE="${EXPORT_WHERE:-}"
    
    TEMP_SEED=$(mktemp)
    
    cat > "$TEMP_SEED" << EOF
-- =======================================
-- Howard County Sidewalk Planning System
-- Seed data init script
-- =======================================
-- Generated by scripts/export_db.sh
-- Contains: Howard County road data (from OpenStreetMap)
-- =======================================

SET session_replication_role = replica;

EOF
    
    echo "-- Base scenarios" >> "$TEMP_SEED"
    pg_dump "$CONN" \
        --data-only \
        --inserts \
        --table=scenarios \
        >> "$TEMP_SEED" 2>/dev/null || echo "-- scenarios empty or missing" >> "$TEMP_SEED"
    
    echo "" >> "$TEMP_SEED"
    echo "-- =======================================" >> "$TEMP_SEED"
    echo "-- Howard County road data" >> "$TEMP_SEED"
    echo "-- =======================================" >> "$TEMP_SEED"
    
    pg_dump "$CONN" \
        --data-only \
        --table=roads_howard \
        >> "$TEMP_SEED" 2>/dev/null || echo "-- roads_howard empty or missing" >> "$TEMP_SEED"
    
    echo "" >> "$TEMP_SEED"
    echo "-- Restore triggers" >> "$TEMP_SEED"
    echo "SET session_replication_role = DEFAULT;" >> "$TEMP_SEED"
    
    echo "" >> "$TEMP_SEED"
    echo "-- Verify import" >> "$TEMP_SEED"
    echo "DO \$\$" >> "$TEMP_SEED"
    echo "DECLARE" >> "$TEMP_SEED"
    echo "    road_count INTEGER;" >> "$TEMP_SEED"
    echo "    scenario_count INTEGER;" >> "$TEMP_SEED"
    echo "BEGIN" >> "$TEMP_SEED"
    echo "    SELECT COUNT(*) INTO road_count FROM roads_howard;" >> "$TEMP_SEED"
    echo "    SELECT COUNT(*) INTO scenario_count FROM scenarios;" >> "$TEMP_SEED"
    echo "    RAISE NOTICE 'Roads: %', road_count;" >> "$TEMP_SEED"
    echo "    RAISE NOTICE 'Scenarios: %', scenario_count;" >> "$TEMP_SEED"
    echo "    " >> "$TEMP_SEED"
    echo "    IF road_count = 0 THEN" >> "$TEMP_SEED"
    echo "        RAISE WARNING 'No road data';" >> "$TEMP_SEED"
    echo "    END IF;" >> "$TEMP_SEED"
    echo "END \$\$;" >> "$TEMP_SEED"
    
    mv "$TEMP_SEED" sql/init/002_seed.sql
    
    SEED_SIZE=$(du -h sql/init/002_seed.sql | cut -f1)
    echo -e "${GREEN}✅ Seed exported to sql/init/002_seed.sql (size: $SEED_SIZE)${NC}"
    
    ROAD_COUNT=$(grep -c "^COPY roads_howard" sql/init/002_seed.sql 2>/dev/null || echo "0")
    if [ "$ROAD_COUNT" -gt 0 ]; then
        echo -e "${GREEN}   📍 Includes road data (COPY format)${NC}"
    fi
fi

echo ""
echo -e "${GREEN}🎉 Export done.${NC}"
echo ""
echo "Next:"
echo "  1. Check generated SQL files"
echo "  2. Commit to Git"
echo "  3. On new server:"
echo "     cp .env.example .env"
echo "     # Edit .env with your keys"
echo "     docker compose up -d --build"
echo ""
